### ISSUE TITLE
Sub-directories don't work with -m=git

### ISSUE THREAD

**Issue by oliversturm** [tiged/tiged#14]
Cloning just a sub-directory of a repo works correctly when using default (`tar`?) mode, but the entire repo is cloned when I use `git` mode, with the sub-directory name ignored. Note that the status message is the same each time, but the result is different.

For this demo I chose a random public repo of mine. The content displayed for the `test-https` case is correct, that's the content of the [config sub-directory of the repo](https://github.com/oliversturm/demo-react-rdserver-client/tree/master/config). In the second case, the content shown for the `test-git` case is incorrect, it is [the complete repo](https://github.com/oliversturm/demo-react-rdserver-client) that has been copied.

```
> npx tiged oliversturm/demo-react-rdserver-client/config ./test-https
... cloned oliversturm/demo-react-rdserver-client#HEAD to ./test-https

> ll test-https
total 64
drwxrwxr-x 3 sturm sturm  4096 Mar 25 16:21 .
drwxr-xr-x 5 sturm sturm  4096 Mar 25 16:21 ..
-rw-r--r-- 1 sturm sturm  3489 Jul 22  2019 env.js
drwxrwxr-x 2 sturm sturm  4096 Mar 25 16:21 jest
-rw-r--r-- 1 sturm sturm  2396 Jul 22  2019 modules.js
-rw-r--r-- 1 sturm sturm  2732 Jul 22  2019 paths.js
-rw-r--r-- 1 sturm sturm   620 Jul 22  2019 pnpTs.js
-rw-r--r-- 1 sturm sturm 27711 Jul 22  2019 webpack.config.js
-rw-r--r-- 1 sturm sturm  5648 Jul 22  2019 webpackDevServer.config.js

> npx tiged -m=git oliversturm/demo-react-rdserver-client/config ./test-git
... cloned oliversturm/demo-react-rdserver-client#HEAD to ./test-git

> ll test-git
total 464
drwxr-xr-x 6 sturm sturm   4096 Mar 25 16:21 .
drwxr-xr-x 4 sturm sturm   4096 Mar 25 16:21 ..
-rw-r--r-- 1 sturm sturm    310 Mar 25 16:21 .gitignore
-rw-r--r-- 1 sturm sturm   2881 Mar 25 16:21 README.md
drwxr-xr-x 3 sturm sturm   4096 Mar 25 16:21 config
-rw-r--r-- 1 sturm sturm   3862 Mar 25 16:21 package.json
drwxr-xr-x 2 sturm sturm   4096 Mar 25 16:21 public
drwxr-xr-x 2 sturm sturm   4096 Mar 25 16:21 scripts
drwxr-xr-x 2 sturm sturm   4096 Mar 25 16:21 src
-rw-r--r-- 1 sturm sturm 437465 Mar 25 16:21 yarn.lock

>
```

**Comment by nake89** [comment]
Thanks for this bug report. Been busy with my move to new apartment. Sorry for late response.
I replicated this error. Looking into fixing it.

**Comment by computnik** [comment]
Maybe this can be done with a simple fix for lines https://github.com/tiged/tiged/blob/83d5d72b1a8d6f122bd22a71841415afd131af51/src/index.js#L318-L322 (`this._cloneWithGit` function) to be something along the lines of:

```js
async _cloneWithGit(dir, dest) {
  const { subdir } = this.repo;
  await exec(`git clone --depth 1 ${this.repo.ssh} ${dest}`);

  if (!subdir)
    rimrafSync(path.resolve(dest, '.git'));
  else {
    fs.renameSync(`${dest}${subdir}`, tmpDirName) // or any other random name!
    rimrafSync(path.resolve(dest));
    fs.renameSync(tmpDirName, dest)
  }
}
```

**Comment by nake89** [comment]
Fixed
