### ISSUE TITLE
Could Not Download GitLab Archive

### ISSUE THREAD

**Issue by enomws** [tiged/tiged#15]
I believe GitLab changed their archived URL structure which is now causing downloads to fail.

## Steps

1. `npm install -g tiged`
2. `degit gitlab:enom/solid-parcel-starter`

## Current Behaviour

I get the following error:

```
! could not download https://gitlab.com/enom/solid-parcel-starter/repository/archive.tar.gz?ref=b7dfd36b0e237f760f4d2c58900fa320076f0413
```

## Expected Behaviour

I get the following package installed:

```
https://gitlab.com/enom/solid-parcel-starter/-/archive/b7dfd36b0e237f760f4d2c58900fa320076f0413/solid-parcel-starter-b7dfd36b0e237f760f4d2c58900fa320076f0413.tar.gz
```

## Potential Fix

URL change in [src/index.js:266](https://github.com/tiged/tiged/blob/83d5d72b1a8d6f122bd22a71841415afd131af51/src/index.js#L266)

I would normally try to create a pull request but I'm a bit too busy at the moment to do exhaustive testing.

**Comment by nake89** [comment]
Fixed in PR #18  and released in version 2.10.3.
