### ISSUE TITLE
Sourceforge support?

### ISSUE THREAD

**Issue by nake89** [tiged/tiged#22]
I'm wondering should I add it.
Or some other open source code hosting service.
If anybody knows any, feel free to suggest.

**Comment by bernardoadc** [comment]
I'm not familiar with this, what are the benefits?

**Comment by nake89** [comment]
Sourceforge was a open source sharing platform used before github. https://sourceforge.net/
They were bought by some company and they implemented shady tactics like putting in search bar installers in the install files of binaries etc.
From what I gather they have cleaned their act and they still do host some open source projects there. Most projects migrated to GitHub obviously. But I thought there might be some value in this.

I've been busy lately. But I might have time to look at implementing this now. Might be fun too.

**Comment by nake89** [comment]
I'll skip this idea for now. But I'm willing to merge a PR if somebody is interested in coding this feature.
