### ISSUE TITLE
how would you use it from javascript/node?

### ISSUE THREAD

**Issue by cekvenich2** [tiged/tiged#26]
is that supported? degit did not work for me at all.

**Comment by nake89** [comment]
Not sure what you mean. I have not personally used the Javascript API of degit (or tiged).
We have not done modifications to tiged in this part of the system (at least not intentionally).
Can you paste what errors you are getting? I can then try to help more.

**Comment by nake89** [comment]
Closing this for now. You are welcome to open this ticket again if you want.
