### ISSUE TITLE
zlib: unexpected end of file

### ISSUE THREAD

**Issue by yannbf** [tiged/tiged#45]
Hey! Thanks a lot for helping `degit` live on.

There's an issue that happens both in `degit` as well as `tiged` which can get quite annoying, so I'll open it here too if you don't mind.

From @natemoo-re:
> We're using `degit` to power [`create-astro`](https://github.com/snowpackjs/astro/blob/main/packages/create-astro/src/index.ts#L71-L75) and a number of users [have reported](https://github.com/snowpackjs/astro/issues/655) that the CLI throws the following error:
> 
> ```
> zlib: unexpected end of file
> ```
> 
> It looks like a workaround is to clear the cached files in `~/.degit`, but this is confusing because we're explicitly setting `cache: false`.
> 
> I'd be happy to contribute a PR to fix this if I can narrow down the problem!

Duplicate of: https://github.com/Rich-Harris/degit/issues/313

**Comment by nake89** [comment]
Yes, PRs are always welcome here. :) I can also look into this. But I make no promises :D 
I have a ticket here that might be related: https://github.com/tiged/tiged/issues/36

**Comment by nake89** [comment]
Fixed with #36
You can try `noCache: true` or on the command line `--no-cache`.
Left `cache` setting as is as not to break existing functionality. It is however deprecated and will be removed in next major version. Use `offlineMode: true` or `--offline-mode` instead.

**Comment by nake89** [comment]
update from #36:

> I'm unhappy how this works currently.
> Will do a patch version hopefully out today. Technically it all works. But the way tiged parses the opts is not nice. Hence my edited previous post (offlineMode to offline-mode and noCache to no-cache). I definitely want it to work as offlineMode and noCache in the programmatic use.

Will keep this ticket closed and work done on #36. Just thought I should let people know.

**Comment by nake89** [comment]
I take that back. This functionality is quite broken until I fix ticket #36.

**Comment by nake89** [comment]
Fixed it. Just use `--disable-cache` argument or programatically `disableCache: true`
