### ISSUE TITLE
Private bitbucket repos not working with -m=git

### ISSUE THREAD

**Issue by ole-treichel** [tiged/tiged#49]
Thanks for your work.

If I try to `tiged` a private bitbucket repo with a branch and in git-mode (`-m=git`):

```
npx tiged git@bitbucket.org:private/repo.git#branch -m=git --force ./test
```

`tiged` still tries to authenticate with a password (instead of ssh / git):

```
Username for 'https://bitbucket.org':
```

And then fails after providing my username and password, as bitbucket does not seem to support authentication via password anymore:

```
! Command failed: cd ./test; git init; git remote add origin https://bitbucket.org/private/repo git fetch --depth 1 origin branch; git checkout FETCH_HEAD
remote: Bitbucket Cloud recently stopped supporting account passwords for Git authentication.
remote: See our community post for more details: https://atlassian.community/t5/x/x/ba-p/1948231
remote: App passwords are recommended for most use cases and can be created in your Personal settings:
remote: https://bitbucket.org/account/settings/app-passwords/
fatal: Authentication failed for 'https://bitbucket.org/private/repo/'
error: pathspec 'FETCH_HEAD' did not match any file(s) known to git
```

If I try the same command with a github repo everything works fine, inluding git mode via ssh. It seems that git mode is not respected when using a bitbucket repo. 

Would love to switch to github but its a requirement of my workplace to use bitbucket for now.

**Comment by donmccurdy** [comment]
I'm facing the same issue when trying to access a private GitHub repository — `tiged` prompts for a password instead of using SSH.

**Comment by nake89** [comment]
```
    /tmp/qwerty  npx tiged git@github.com:nake89/calendar.git -m=git                                                                                     ✔  16.14.0  
> cloned nake89/calendar#HEAD
    /tmp/qwerty  ls -la                                                                                                                           ✔  4s   16.14.0  
total 104
drwxrwxr-x  2 nake89 nake89   120  3. 9. 15:22 .
drwxrwxrwt 17 root   root     360  3. 9. 15:07 ..
-rw-r--r--  1 nake89 nake89 95956  3. 9. 15:22 cal.txt
-rwxr-xr-x  1 nake89 nake89   102  3. 9. 15:22 get-date.sh
-rw-r--r--  1 nake89 nake89   277  3. 9. 15:22 how-to.txt
-rw-r--r--  1 nake89 nake89     0  3. 9. 15:22 todo.txt
    /tmp/qwerty     
```

Tested this on a private repo and it works for me...

I will be testing this on bitbucket as well. Thanks for the bug report!

**Comment by donmccurdy** [comment]
@nake89 I think the problem with private GitHub repositories occurs only when checking out a specific branch. Checking out the default branch works for me as well.

```shell
# ok
npx tiged git@github.com:donmccurdy/private.git --mode=git .

# fails: `Username for 'https://github.com': ...`
npx tiged git@github.com:donmccurdy/private.git#my-branch --mode=git .
```

**Comment by nake89** [comment]
This is fixed now with newest version.
But it broke git mode with https.
So that kinda sucks maybe. Dunno. Gonna try to make it work with both modes. Give me a day or so to do a fix. Until then use 2.11.2 if you want git mode and https.
