### ISSUE TITLE
! zlib: unexpected end of file

### ISSUE THREAD

**Issue by shinokada** [tiged/tiged#65]
When I fetch a PDF file, it returns `! zlib: unexpected end of file`.

```
$ tiged shinokada/markdown-docs-as-pdf/pdf/slidev/en
! zlib: unexpected end of file
```

And reactjs:

```
$ tiged reactjs/it.reactjs.org/content
! zlib: unexpected end of file
```

But it fetch a file.

```
$ ls
slidev-en.pdf
```

**Comment by nake89** [comment]
I cannot replicate this. I am not getting this error.
I think it got fixed in: https://github.com/tiged/tiged/issues/45
If you are still experiencing this issue try:
You can try `no-cache: true` or on the command line `--no-cache`.
