### ISSUE TITLE
feat: add support for alternate github urls

### ISSUE THREAD

**Issue by kennyg** [tiged/tiged#80]
would it be possible to add an option to support alternate github urls? for example, internal github servers?

**Comment by nake89** [comment]
Sorry for late reply. Private repositories are supported. Not sure if that is what you mean.

Could you give me an example of this internal github server. Feel free to obfuscate it if it is necessary. I just need some sort of example to understand this.

**Comment by kennyg** [comment]
> Sorry for late reply. Private repositories are supported. Not sure if that is what you mean.
> 
> 
> 
> Could you give me an example of this internal github server. Feel free to obfuscate it if it is necessary. I just need some sort of example to understand this.

For example, ghe.mycompany.com is an internal GitHub enterprise server. Might it be possible to add support for a way to specify the GitHub hostname via an environment variable, like GH_HOST and everything just work?

**Comment by nake89** [comment]
So for `--mode=git` this should already work. If Github Enterprise supports the tar.gz file and it is in the same path as it is in github, you can try to use `--mode=tar`.
