### ISSUE TITLE
--force does not work with --mode=git

### ISSUE THREAD

**Issue by oodavid** [tiged/tiged#81]
Firstly, make a non-empty directory:

```
touch test.txt
```

Then run tiged with `--mode=git`, and get the expected error:

```
npx --yes tiged --mode=git tiged/tiged-test .
! destination directory is not empty, aborting. Use --force to override
```

Add `--force` as advised and we see a similar (git) error:

```
npx --yes tiged --mode=git tiged/tiged-test . --force
> destination directory is not empty. Using --force, continuing
! Command failed: git clone --depth 1 git@tiged/tiged-test .
fatal: destination path '.' already exists and is not an empty directory.
```

**Comment by oodavid** [comment]
To solve my specific use-case, where we only care about one directory (src) I've done the following

Setting up a test directory

```shell
mkdir ./src & touch ./src/local.file
```

Then the command to clone and "merge"

```shell
npx --yes tiged --mode=git oodavid/stackblitz-test tmp --force
mv -v ./src/* ./tmp/src
rm -d ./src
mv -f ./tmp/* ./
mv -f ./tmp/.* ./
rm -d ./tmp
```

**Comment by oodavid** [comment]
I've had better luck with rsync. It gives better control over the merging of files, and reads more sensibly:

```shell
npx --yes tiged --mode=git tiged/tiged-test tmp
rsync -a ./tmp/ ./
rm -rf ./tmp
```

**Comment by nake89** [comment]
Looking at the code it should delete the folder if `--force` is used regardless of whether or not gitmode is used. I wonder if is because you have put --force at the end of the command.

**Comment by nake89** [comment]
```
➜  /tmp cd asdasd
➜  asdasd mkdir testi
➜  asdasd cd testi
➜  testi vim file
➜  testi cd ..
➜  asdasd tiged --mode=git --force tiged/tiged testi
> destination directory is not empty. Using --force, continuing
> cloned tiged/tiged#HEAD to testi
```

Could not replicate. Closing ticket. If you still think still is broken feel free to open this ticket or a new one.
