### ISSUE TITLE
add typescript support

### ISSUE THREAD

**Issue by beenotung** [tiged/tiged#85]
This package doesn't has typescript support out of the box.
Is it having the same type signature as degit?
If so, we can copy @types/degit into @types/tiged.

**Comment by nake89** [comment]
That is indeed a good idea.

**Comment by aryaemami59** [comment]
@nake89 is this still up for consideration? If so I would love to help out! would be interested in a PR?

**Comment by nake89** [comment]
Yeah, a PR sounds great. :)

**Comment by aryaemami59** [comment]
@nake89
> Yeah, a PR sounds great. :)

Awesome, one PR coming right up!
