### ISSUE TITLE
Support HTTPS_PROXY

### ISSUE THREAD

**Issue by PeterlitsZo** [tiged/tiged#86]
I create a PR here: https://github.com/Rich-Harris/degit/pull/368

I think maybe you are also interested. If you guys do so, I can also copy that here.

**Comment by PeterlitsZo** [comment]
Hello? I think I need some reply...

**Comment by nake89** [comment]
I haven't used this feature. So does it currently only work with lowercase
environment variable? I've never seen lowercase env vars used before. Your
fix makes it work with both it seems, keeping it backwards compatible.

**Comment by PeterlitsZo** [comment]
[This post](https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/) discusses a lot about those proxy environment variables.

Yes, the current version of it now only supports `https_proxy` but not `HTTPS_PROXY`. Supporting `HTTPS_PROXY` sounds not bad to me - like what HTTPie does.

Why do people need this feature (I mean, the proxy)? There are many reasons I guess - maybe they are in the limited network (e.g. company) or something else. For me, because it is firstly a fact standard and I also need this feature to access GitHub resources (I am not sure but maybe there are some country do not allow people to access some websites directly) - I do not want to talk about it too much.

Yes, my change can help tiged use both `https_proxy` and `HTTPS_PROXY`. I think it's a good change. If you approve it, I will create a PR and try to let `create-hono` switch from degit to tiged also.

**Comment by PeterlitsZo** [comment]
Here is how does Python's library urllib work - https://docs.python.org/3/library/urllib.request.html#urllib.request.getproxies

**Comment by nake89** [comment]
Sounds good. I'll try to get it merged soon.

**Comment by PeterlitsZo** [comment]
I plan to send a PR today (happy weekend) but I am surprised that you have already committed my commit. Thank you.

Please close this issue if you think this is done.
