### ISSUE TITLE
Add support for Codeberg

### ISSUE THREAD

**Issue by joaopalmeiro** [tiged/tiged#94]
Hi! 👋 

Similarly to other providers like GitLab and sourcehut, I would like to propose _officially_ supporting [Codeberg](https://codeberg.org/). 

At the moment, as far as I've tested, it is possible to download a Codeberg repository (e.g., `npx tiged https://codeberg.org/joaopalmeiro/template-figma-plugin-script`), but support for Codeberg is not documented and there is no _shortcut_ for it: https://github.com/tiged/tiged/blob/c0537f7e4d9bec9d964be66b0b454c71f89ee572/src/index.ts#L772-L778

If I'm correct, it's even possible to download a Codeberg repository in `tar` mode since the following URL corresponds to the Codeberg one (e.g., https://codeberg.org/joaopalmeiro/template-figma-plugin-script/archive/main.tar.gz): https://github.com/tiged/tiged/blob/c0537f7e4d9bec9d964be66b0b454c71f89ee572/src/index.ts#L655

As an alternative, it is also possible to use the [Codeberg API](https://codeberg.org/api/swagger#/repository/repoGetArchive).

Let me know what you think, please. If you think supporting Codeberg makes sense, let me know if I can open a PR.

Thanks!

**Comment by nake89** [comment]
This is an awesome suggestion. Please post a PR and I will happily merge it.

**Comment by joaopalmeiro** [comment]
I'll work on it. Thanks!
